name: Build Installers

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows installer
      if: matrix.os == 'windows'
      run: flutter build windows

    - name: Package installers
      if: matrix.os == 'windows'
      run: |
        mkdir MyAppInstaller
        xcopy /E /Y build\windows\Runner\Release MyAppInstaller
        7z a MyAppInstaller.zip MyAppInstaller

    - name: Upload installers
      uses: actions/upload-artifact@v2
      with:
        name: windows-installer
        path: ${{ github.workspace }}/MyAppInstaller.zip

    - name: Send Telegram message
      if: always()
      run: |
        curl -s -X POST https://api.telegram.org/bot${{secrets.BOTTOKEN}}/sendMessage -d "chat_id=${{secrets.CHATID}}&text=New Windows installer available for download!\n\nProject: Flutter - Application\Committed Actor: ${{ github.actor }}" > nul


    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v1
      if: always()
      with:
        name: windows-installer
        failOnError: false

    strategy:
      matrix:
        os: ['windows']
