name: Send Telegram Message

on:
  push:
    branches:
    - master

jobs:
  send_message:
    runs-on: windows-latest

    steps:
    - name: Send Telegram Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.MESSAGEID }}
        token: ${{ secrets.BOTTOKEN }}
        message: "Automated Message from Github!"
