name: Build and Send Windows

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Send build to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        document: "build/windows/runner/Release/app.exe"
        message: "Hello there...!!!"
