name: Send Telegram Message

on:
  push:
    branches:
    - master

jobs:
  send_message:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run PowerShell Script
      shell: pwsh
      run: .\send_telegram_message.ps1
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.BOTTOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.MESSAGEID }}
